version: "3.8"
services: 

  # Redis
  redis:
    image: redis:5
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./data/db:/var/
    restart: always
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=scheduler
    container_name: scheduler_db

  django:
    build: .
    container_name: scheduler_backend
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=scheduler
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=scheduler
    depends_on:
      - db
    
  celery:
    restart: always
    build: 
      context: .
    command: celery -A sm_scheduler worker -l info 
    volumes: 
      - .:/app
    container_name: celery
    environment:
      - POSTGRES_DB=scheduler
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=scheduler
    depends_on:
      - redis
      - db
      - django

