# Generated by Django 4.2.1 on 2023-07-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='access_token_secret',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
