# Generated by Django 4.2.1 on 2023-07-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_integration', '0002_socialmediaaccount_access_token_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='access_token_secret',
        ),
    ]
