# Generated by Django 4.2.1 on 2023-07-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_integration', '0003_remove_socialmediaaccount_access_token_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='access_token_secret',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
