# Generated by Django 4.2.1 on 2023-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_integration', '0004_socialmediaaccount_access_token_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='username',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
