# Generated by Django 4.2.1 on 2023-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_integration', '0005_socialmediaaccount_name_socialmediaaccount_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaaccount',
            name='profile_picture_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
